controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\IndexController::index

categories:
    path: /category
    controller: App\Controller\CategoriesController::category

panier:
    path: /basket
    controller: App\Controller\BasketController::basket


